### ISSUE TITLE
need up bump k8s client-go

### ISSUE THREAD

**Issue by mosinnik** [ydb-platform/ydb-kubernetes-operator#225]
faced with https://github.com/kubernetes/kubernetes/issues/119840 caused by 0.26.1 client lib, need to bump up

kube server: 1.27.4
ydb-operator: 0.5.16

operator stack:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1387930]

goroutine 1 [running]:
2024-06-28T14:32:46.626099053+03:00 k8s.io/client-go/discovery.convertAPIResource(...)
	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:88
2024-06-28T14:32:46.626102728+03:00 k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00005cd20, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
2024-06-28T14:32:46.626106382+03:00 	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:69 +0x570
2024-06-28T14:32:46.626114407+03:00 k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc0004ac228, 0x15}, {0xc000161b80, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
2024-06-28T14:32:46.626116509+03:00 	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:35 +0x118
2024-06-28T14:32:46.626118252+03:00 k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x10b4894?)
2024-06-28T14:32:46.626119958+03:00 	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:310 +0x47c
2024-06-28T14:32:46.626121658+03:00 k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0x138bb73?)
2024-06-28T14:32:46.626123626+03:00 	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:198 +0x5c
2024-06-28T14:32:46.626125463+03:00 k8s.io/client-go/discovery.ServerGroupsAndResources({0x20e6650, 0xc000493aa0})
2024-06-28T14:32:46.626127587+03:00 	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:392 +0x59
2024-06-28T14:32:46.626129500+03:00 k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
2024-06-28T14:32:46.626132507+03:00 	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:356 +0x25
2024-06-28T14:32:46.626135083+03:00 k8s.io/client-go/discovery.withRetries(0x2, 0xc0007030f0)
2024-06-28T14:32:46.626137809+03:00 	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:621 +0x71
2024-06-28T14:32:46.626140287+03:00 k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
2024-06-28T14:32:46.626143007+03:00 	/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:355 +0x3a
2024-06-28T14:32:46.626145878+03:00 k8s.io/client-go/restmapper.GetAPIGroupResources({0x20e6650?, 0xc000493aa0?})
	/go/pkg/mod/k8s.io/client-go@v0.26.1/restmapper/discovery.go:148 +0x42
2024-06-28T14:32:46.626150869+03:00 sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
2024-06-28T14:32:46.626154167+03:00 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:86 +0x25
2024-06-28T14:32:46.626155930+03:00 sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
2024-06-28T14:32:46.626157734+03:00 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:119
2024-06-28T14:32:46.626159490+03:00 sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc00011cc60?, {0x0, 0x0, 0x70cd29ebd3c5a801?})
2024-06-28T14:32:46.626161356+03:00 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:99 +0x176
2024-06-28T14:32:46.626163119+03:00 sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0xc0002fd9d0?)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/cluster/cluster.go:217 +0x25
2024-06-28T14:32:46.626166820+03:00 sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc00051bd40, {0xc0004d1a70, 0x1, 0x0?})
2024-06-28T14:32:46.626172608+03:00 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/cluster/cluster.go:159 +0x18d
2024-06-28T14:32:46.626175078+03:00 sigs.k8s.io/controller-runtime/pkg/manager.New(_, {0xc0002fd9d0, 0x0, 0x0, {{0x20df378, 0xc000050080}, 0x0}, 0x1, {0x0, 0x0}, ...})
2024-06-28T14:32:46.626177454+03:00 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/manager/manager.go:351 +0xf9
2024-06-28T14:32:46.626180038+03:00 main.main()
	/workspace/cmd/ydb-kubernetes-operator/main.go:70 +0x4f5
```

**Comment by kobzonega** [comment]
Hello, @mosinnik 
Thank you for the help to find the bug. I think it was fixed at #234 with ydb-operator helm chart and docker image release version 0.5.23
